### ISSUE TITLE
/g info

### ISSUE THREAD

**Issue by Psycho611** [rplcnn/SuperGuilds#15]
When i use that command i get this

[14:29:56] [Server thread/INFO]: Psycho611 issued server command: /g create GodOfCraft GOC
[14:29:56] [Server thread/INFO]: Psycho611: /g create GodOfCraft GOC
[14:29:56] [Server thread/INFO]: Psycho611: /sg claim
[14:29:56] [Server thread/INFO]: Guildsâž   Player Psycho611, created GodOfCraft guild.
[14:30:10] [Server thread/INFO]: Psycho611 issued server command: /gm 1
[14:30:13] [Server thread/INFO]: CONSOLE issued server command: /list 
[14:30:13] [Server thread/INFO]: There are 1 out of maximum 60 players online.
[14:30:13] [Server thread/INFO]: Admins: [Owner] Psycho611
[14:30:19] [Server thread/INFO]: <[GOC] Psycho611> asd
[14:30:29] [Server thread/INFO]: Psycho611 issued server command: /g info
[14:30:29] [Server thread/INFO]: Psycho611: /g info
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[14:30:29] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[14:30:29] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[14:30:29] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[14:30:29] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[14:30:29] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[14:30:29] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! Stack trace:
[14:30:29] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
[14:30:29] [Server thread/ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:59)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:32)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory(CraftServer.java:1530)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:934)
[14:30:29] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:36)
[14:30:29] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:14)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:61)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:78)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[14:30:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:85)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:30:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[14:30:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
[14:30:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[14:30:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[14:30:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[14:30:29] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! Version Information:
[14:30:29] [Server thread/ERROR]: #!#!   Skript: 2.1.2
[14:30:29] [Server thread/ERROR]: #!#!   Bukkit: 1.8.6-R0.1-SNAPSHOT
[14:30:29] [Server thread/ERROR]: #!#!   Minecraft: 1.8.6
[14:30:29] [Server thread/ERROR]: #!#!   Java: 1.8.0_45
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! Current node: null
[14:30:29] [Server thread/ERROR]: #!#! Current item: open inventory to the player
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! Thread: Server thread
[14:30:29] [Server thread/ERROR]: #!#! 
[14:30:29] [Server thread/ERROR]: #!#! End of Error.
[14:30:29] [Server thread/ERROR]: #!#!

**Comment by rplcnn** [comment]
Fixed Thank you :)
