### ISSUE TITLE
When i create a guild the build doesnt appear

### ISSUE THREAD

**Issue by powext** [rplcnn/SuperGuilds#75]
Error in conole:
[18:03:08 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_10_R1.WorldServer.makeSound(double, double, double, java.lang.String, float, float)
[18:03:08 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[18:03:08 WARN]:        at com.w00tmast3r.skquery.elements.effects.EffCustomSound.execute(EffCustomSound.java:38)
[18:03:08 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:54)
[18:03:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:03:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:03:08 WARN]:        at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[18:03:08 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[18:03:08 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:03:08 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
[18:03:08 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[18:03:08 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[18:03:08 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[18:03:08 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by rplcnn** [comment]
Hmm, thank you.
