### ISSUE TITLE
Buildings doesn't work... 

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [rplcnn/SuperGuilds#83]
Dear... when I create new guild... the builds doesn't spawn.

Latest version of all

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
this is the pastebin

`https://pastebin.com/pL8cRF03`

And in the guild menu, there are many bugs. We cannot see the deposit lingot and buttons... and there are no builds in the build menu

**Comment by rplcnn** [comment]
Hmm thanks, seems you are using it_IT locale. Its outdated and buildings won't work. Try to use en_US, i will fix it soon.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I put it on english... but it's not this the problem

https://pastebin.com/sg5RWSms

Buildings buttons doesn't exist , doesn't appears... also in the deposit...

**Comment by rplcnn** [comment]
Can you try /g sync en_US

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
if I do this command, he tell me to put the file to sync it (loce or config)

I don't know what it means...

**Comment by rplcnn** [comment]
./g sync locale

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
No... it's always the same. But I don't think that it's aproblem of language.  Anyway I did it but doesn't work... if you want to come to see by yourself...

mc.herosfaith.eu

let me know if u come becouse I have to open the server

**Comment by rplcnn** [comment]
okay

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
ok let me know

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
hey?

**Comment by Fargus5** [comment]
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[10:06:50] [Server thread/ERROR]: #!#! Could not load SUPERGUILDS_wars.sk
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[10:06:50] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[10:06:50] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[10:06:50] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[10:06:50] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[10:06:50] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[10:06:50] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! Stack trace:
[10:06:50] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1417)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1138)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:745)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:745)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:450)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[10:06:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
[10:06:50] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[10:06:50] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[10:06:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[10:06:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[10:06:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[10:06:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[10:06:50] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! Version Information:
[10:06:50] [Server thread/ERROR]: #!#!   Skript: 2.2-dev29
[10:06:50] [Server thread/ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[10:06:50] [Server thread/ERROR]: #!#!   Minecraft: 1.12
[10:06:50] [Server thread/ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[10:06:50] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-std-ipv6-64
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! Current node: set {_Lobby} to location of block at location ({_x}, {_y}, {_z}) in world {_w} (SUPERGUILDS_wars.sk, line 533)
[10:06:50] [Server thread/ERROR]: #!#! Current item: null
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! Thread: Server thread
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: #!#! End of Error.
[10:06:50] [Server thread/ERROR]: #!#! 
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: open chest with 1 row named "&8[&4&lAnti-XRay&8]" to player (axr.sk, line 80: open chest with 1 row named "&8[&4&lAnti-XRay&8]" to player')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 0 of player with a coal ore named "%{coal.name}%" to close then run [execute player command "/axrsettings12 coal"] (axr.sk, line 81: format slot 0 of player with a coal ore named "%{coal.name}%" to close then run [execute player command "/axrsettings12 coal"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 1 of player with a iron ore named "%{iron.name}%" to close then run [execute player command "/axrsettings12 iron"] (axr.sk, line 82: format slot 1 of player with a iron ore named "%{iron.name}%" to close then run [execute player command "/axrsettings12 iron"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 2 of player with a gold ore named "%{gold.name}%" to close then run [execute player command "/axrsettings12 gold"] (axr.sk, line 83: format slot 2 of player with a gold ore named "%{gold.name}%" to close then run [execute player command "/axrsettings12 gold"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 3 of player with redstone_ore_off named "%{red.name}%" to close then run [execute player command "/axrsettings12 red"] (axr.sk, line 84: format slot 3 of player with redstone_ore_off named "%{red.name}%" to close then run [execute player command "/axrsettings12 red"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 4 of player with a lapis lazuli ore named "%{blue.name}%" to close then run [execute player command "/axrsettings12 blue"] (axr.sk, line 85: format slot 4 of player with a lapis lazuli ore named "%{blue.name}%" to close then run [execute player command "/axrsettings12 blue"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 5 of player with a emerald ore named "%{green.name}%" to close then run [execute player command "/axrsettings12 green"] (axr.sk, line 86: format slot 5 of player with a emerald ore named "%{green.name}%" to close then run [execute player command "/axrsettings12 green"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 6 of player with a diamond ore named "%{diamond.name}%" to close then run [execute player command "/axrsettings12 diamond"] (axr.sk, line 87: format slot 6 of player with a diamond ore named "%{diamond.name}%" to close then run [execute player command "/axrsettings12 diamond"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: open chest with 1 row named "&8[&4&lAnti-XRay&8]" to player (axr.sk, line 93: open chest with 1 row named "&8[&4&lAnti-XRay&8]" to player')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 0 of player with a coal ore named "%{coal.name}%" to close then run [execute player command "/axrsettings12 coal"] (axr.sk, line 94: format slot 0 of player with a coal ore named "%{coal.name}%" to close then run [execute player command "/axrsettings12 coal"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 1 of player with a iron ore named "%{iron.name}%" to close then run [execute player command "/axrsettings12 iron"] (axr.sk, line 95: format slot 1 of player with a iron ore named "%{iron.name}%" to close then run [execute player command "/axrsettings12 iron"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 2 of player with a gold ore named "%{gold.name}%" to close then run [execute player command "/axrsettings12 gold"] (axr.sk, line 96: format slot 2 of player with a gold ore named "%{gold.name}%" to close then run [execute player command "/axrsettings12 gold"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 3 of player with redstone_ore_off named "%{red.name}%" to close then run [execute player command "/axrsettings12 red"] (axr.sk, line 97: format slot 3 of player with redstone_ore_off named "%{red.name}%" to close then run [execute player command "/axrsettings12 red"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 4 of player with a lapis lazuli ore named "%{blue.name}%" to close then run [execute player command "/axrsettings12 blue"] (axr.sk, line 98: format slot 4 of player with a lapis lazuli ore named "%{blue.name}%" to close then run [execute player command "/axrsettings12 blue"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 5 of player with a emerald ore named "%{green.name}%" to close then run [execute player command "/axrsettings12 green"] (axr.sk, line 99: format slot 5 of player with a emerald ore named "%{green.name}%" to close then run [execute player command "/axrsettings12 green"]')
[10:06:50] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: format slot 6 of player with a diamond ore named "%{diamond.name}%" to close then run [execute player command "/axrsettings12 diamond"] (axr.sk, line 100: format slot 6 of player with a diamond ore named "%{diamond.name}%" to close then run [execute player command "/axrsettings12 diamond"]')
[10:06:51] [Server thread/INFO]: [Skript] Loaded 9 scripts with a total of 46 triggers and 12 commands in 7.44 seconds
[10:06:51] [Server thread/INFO]: [Skript] Finished loading.
